### ISSUE TITLE
FastFlix v4.0.0 Windows Installer - Unable to launch

### ISSUE THREAD

**Issue by pcf1** [cdgriffith/FastFlix#141]
Hello,

Fresh install, no previous versions.
It launches, offers to download ffmpeg, I agree, it finishes downloading then closes.

Log file below:
```
2020-12-27 22:57:51,779 - fastflix      INFO     Running command: None -version
2020-12-27 22:57:51,782 - fastflix      ERROR    Could not run task Gather FFmpeg version with config Config(version='4.0.0', config_path=WindowsPath('C:/Users/user/AppData/Roaming/FastFlix/fastflix.yaml'), ffmpeg=None, ffprobe=None, language='en', continue_on_failure=True, work_path=WindowsPath('C:/Users/user/AppData/Roaming/FastFlix'), use_sane_audio=True, selected_profile='Standard Profile', disable_version_check=False, disable_update_check=False, disable_automatic_subtitle_burn_in=False, custom_after_run_scripts={}, profiles={'Standard Profile': Profile(auto_crop=False, keep_aspect_ratio=True, fast_seek=True, rotate=0, vertical_flip=False, horizontal_flip=False, copy_chapters=True, remove_metadata=True, remove_hdr=False, encoder='HEVC (x265)', audio_language='en', audio_select=True, audio_select_preferred_language=True, audio_select_first_matching=False, subtitle_language='en', subtitle_select=True, subtitle_select_preferred_language=True, subtitle_automatic_burn_in=True, subtitle_select_first_matching=False, x265=x265Settings(max_muxing_queue_size='1024', pix_fmt='yuv420p10le', extra='', preset='medium', intra_encoding=False, profile='default', tune='default', hdr10=False, hdr10_opt=False, dhdr10_opt=False, repeat_headers=False, aq_mode=2, hdr10plus_metadata='', crf=None, bitrate=None, x265_params=[], bframes=4, lossless=False, b_adapt=2, intra_refresh=False, intra_smoothing=True, frame_threads=0), x264=None, rav1e=None, svt_av1=None, vp9=None, aom_av1=None, gif=None, webp=None, copy=None), 'UHD HDR10 Film': Profile(auto_crop=True, keep_aspect_ratio=True, fast_seek=True, rotate=0, vertical_flip=False, horizontal_flip=False, copy_chapters=True, remove_metadata=True, remove_hdr=False, encoder='HEVC (x265)', audio_language='en', audio_select=True, audio_select_preferred_language=True, audio_select_first_matching=False, subtitle_language='en', subtitle_select=True, subtitle_select_preferred_language=True, subtitle_automatic_burn_in=True, subtitle_select_first_matching=False, x265=x265Settings(max_muxing_queue_size='1024', pix_fmt='yuv420p10le', extra='', preset='slow', intra_encoding=False, profile='default', tune='default', hdr10=True, hdr10_opt=True, dhdr10_opt=False, repeat_headers=True, aq_mode=2, hdr10plus_metadata='', crf=18, bitrate=None, x265_params=[], bframes=4, lossless=False, b_adapt=2, intra_refresh=False, intra_smoothing=True, frame_threads=0), x264=None, rav1e=None, svt_av1=None, vp9=None, aom_av1=None, gif=None, webp=None, copy=None), '1080p Film': Profile(auto_crop=True, keep_aspect_ratio=True, fast_seek=True, rotate=0, vertical_flip=False, horizontal_flip=False, copy_chapters=True, remove_metadata=True, remove_hdr=False, encoder='AVC (x264)', audio_language='en', audio_select=True, audio_select_preferred_language=True, audio_select_first_matching=False, subtitle_language='en', subtitle_select=True, subtitle_select_preferred_language=True, subtitle_automatic_burn_in=True, subtitle_select_first_matching=False, x265=None, x264=x264Settings(max_muxing_queue_size='1024', pix_fmt='yuv420p', extra='', preset='slow', profile='default', tune='default', crf=17, bitrate=None), rav1e=None, svt_av1=None, vp9=None, aom_av1=None, gif=None, webp=None, copy=None)}, sane_audio_selection=['aac', 'ac3', 'alac', 'dca', 'dts', 'eac3', 'flac', 'libfdk_aac', 'libmp3lame', 'libopus', 'libvorbis', 'libwavpack', 'snoicls', 'sonic', 'truehd', 'tta'])
Traceback (most recent call last):
  File "fastflix\widgets\progress_bar.py", line 83, in run
    task.command(config=self.app.fastflix.config, app=self.app, **task.kwargs)
  File "fastflix\flix.py", line 89, in ffmpeg_configuration
    res = execute([f"{config.ffmpeg}", "-version"])
  File "fastflix\flix.py", line 76, in execute
    return run(
  File "subprocess.py", line 501, in run
  File "subprocess.py", line 947, in __init__
  File "subprocess.py", line 1416, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
2020-12-27 22:57:51,784 - fastflix      ERROR    Exception in 'run': [WinError 2] The system cannot find the file specified - args: (<fastflix.widgets.progress_bar.ProgressBar object at 0x0000023F0DBA7160>,)
Traceback (most recent call last):
  File "reusables\wrappers.py", line 285, in wrapper
  File "fastflix\widgets\progress_bar.py", line 83, in run
    task.command(config=self.app.fastflix.config, app=self.app, **task.kwargs)
  File "fastflix\flix.py", line 89, in ffmpeg_configuration
    res = execute([f"{config.ffmpeg}", "-version"])
  File "fastflix\flix.py", line 76, in execute
    return run(
  File "subprocess.py", line 501, in run
  File "subprocess.py", line 947, in __init__
  File "subprocess.py", line 1416, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by cdgriffith** [comment]
Thanks for the report, will fix that asap. For now, relaunching it again should allow it to work fine.

**Comment by thunderclap82** [comment]
Same issue, and a relaunch doesn’t fix it. Asks to download ffmpeg again.

**Comment by pcf1** [comment]
Thank you,

Relaunching it again causes it to offer to re-download ffmpeg (again), even though the following folder is already populated by it's files:
c:\Users\user\AppData\Roaming\FFmpeg\
c:\Users\alderaan\AppData\Roaming\FFmpeg\bin\
c:\Users\alderaan\AppData\Roaming\FFmpeg\doc\

BTW: don't know if I'm throttled now somehow but the ffmpeg download is taking ages now, instead of ~15 seconds.

**Comment by pcf1** [comment]
> Thanks for the report, will fix that asap. For now, relaunching it again should allow it to work fine.

Thank you,

Relaunching it again causes it to offer to re-download ffmpeg (again), even though the following folder is already populated by it's files:
c:\Users\user\AppData\Roaming\FFmpeg
c:\Users\alderaan\AppData\Roaming\FFmpeg\bin
c:\Users\alderaan\AppData\Roaming\FFmpeg\doc\

BTW: don't know if I'm throttled now somehow but the ffmpeg download is taking ages now, instead of ~15 seconds.

**Comment by cdgriffith** [comment]
Very odd, I will try to re-create that behavior and see what's going on.

For time being, can manually create the config file with proper paths to fix it: 

`C:\Users\<your_user_name>\AppData\Roaming\FastFlix\fastflix.yaml`

```
continue_on_failure: true
custom_after_run_scripts: {}
disable_automatic_subtitle_burn_in: false
disable_update_check: false
disable_version_check: false
ffmpeg: C:\Users\<your_user_name>\AppData\Roaming\FFmpeg\bin\ffmpeg.exe
ffprobe: C:\Users\<your_user_name>\AppData\Roaming\FFmpeg\bin\ffprobe.exe
language: en
profiles: {}
sane_audio_selection:
- aac
- ac3
- alac
- dca
- dts
- eac3
- flac
- libfdk_aac
- libmp3lame
- libopus
- libvorbis
- libwavpack
- snoicls
- sonic
- truehd
- tta
selected_profile: Standard Profile
use_sane_audio: true
version: 4.0.0
work_path: C:\Users\<your_user_name>\AppData\Roaming\FastFlix
```

**Comment by pcf1** [comment]
> Very odd, I will try to re-create that behavior and see what's going on.
> 
> For time being, can manually create the config file with proper paths to fix it:
> 
> `C:\Users\<your_user_name>\AppData\Roaming\FastFlix\fastflix.yaml`

FastFlix's UI loads. Thank you.

**Comment by cdgriffith** [comment]
Hopefully this fixes this issue https://github.com/cdgriffith/FastFlix/releases/tag/4.0.1b0 for anyone else experiencing it.  

Will wait a few hours for any other Day 0 bugs from the 4.0 release and release it officially tonight or tomorrow morning.

**Comment by thunderclap82** [comment]
> Hopefully this fixes this issue https://github.com/cdgriffith/FastFlix/releases/tag/4.0.1b0 for anyone else experiencing it.
> 
> Will wait a few hours for any other Day 0 bugs from the 4.0 release and release it officially tonight or tomorrow morning.

Appears to fix the issue. I just ran the executable in the ZIP and everything started no problem.

**Comment by cdgriffith** [comment]
Fixed in https://github.com/cdgriffith/FastFlix/releases/tag/4.0.1
