### ISSUE TITLE
OSX starting FastFlix - _execute_child PermissionError: /ffmpeg/4.4_2/bin

### ISSUE THREAD

**Issue by Hudaldadi** [cdgriffith/FastFlix#250]
Traceback (most recent call last):
  File "fastflix/application.py", line 158, in start_app
    ProgressBar(app, startup_tasks)
  File "fastflix/widgets/progress_bar.py", line 60, in __init__
    self.run()
  File "reusables/wrappers.py", line 293, in wrapper
  File "reusables/wrappers.py", line 285, in wrapper
  File "fastflix/widgets/progress_bar.py", line 86, in run
    task.command(config=self.app.fastflix.config, app=self.app, **task.kwargs)
  File "fastflix/flix.py", line 93, in ffmpeg_configuration
    res = execute([f"{config.ffmpeg}", "-version"])
  File "fastflix/flix.py", line 80, in execute
    return run(
  File "subprocess.py", line 493, in run
  File "subprocess.py", line 858, in __init__
  File "subprocess.py", line 1704, in _execute_child
PermissionError: [Errno 13] Permission denied: '/usr/local/Cellar/ffmpeg/4.4_2/bin'

After FFmpeg and FFprobe was installed and path updated.
Got this permission issue.

**Comment by cdgriffith** [comment]
The user running FastFlix doesn't seem to have perms to execute ffmpeg. What are it's permissions? 

You can check with `ls -lah /usr/local/Cellar/ffmpeg/4.4_2/bin`  and either add execute for "others" or run FastFlix as that user.

**Comment by schlotkins** [comment]
I'm also having an issue with FFMpeg. It asked to update and then didn't work. Now it says FFmpeg isn't installed and asks to download. It downloads but then crashes out and doesn't install. 

Thanks!
Chris
