### ISSUE TITLE
Crash at start, Windows pre-build or start from Source

### ISSUE THREAD

**Issue by lobofoots** [cdgriffith/FastFlix#264]
I update Fastflix today and it won't start properly.
I tried to start it from source and this is the output
`$ python -m fastflix
2021-09-26 10:55:02 GAMER fastflix-core[6940] INFO Starting FastFlix 4.4.1
2021-09-26 10:55:03 GAMER fastflix[1260] DEBUG Using config file C:\Users\Admin\AppData\Roaming\FastFlix\fastflix.yaml
2021-09-26 10:55:03 GAMER fastflix[1260] INFO Running command: c:\ffmpeg\bin\ffmpeg.EXE -version
2021-09-26 10:55:03 GAMER fastflix[1260] INFO Running command: c:\ffmpeg\bin\ffprobe.EXE -version
2021-09-26 10:55:03 GAMER fastflix[1260] INFO Running command: c:\ffmpeg\bin\ffmpeg.EXE -hide_banner -encoders
Could not start GUI process - Error: 'charmap' codec can't decode byte 0x90 in position 127: character maps to <undefined>
Process Process-2:
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\eac3to\FastFlix\fastflix\entry.py", line 38, in separate_app_process
    raise err
  File "C:\eac3to\FastFlix\fastflix\entry.py", line 35, in separate_app_process
    start_app(worker_queue, status_queue, log_queue, queue_list, queue_lock)
  File "C:\eac3to\FastFlix\fastflix\application.py", line 171, in start_app
    container = Container(app)
  File "C:\eac3to\FastFlix\fastflix\widgets\container.py", line 41, in __init__
    self.changes = Changes()
  File "C:\eac3to\FastFlix\fastflix\widgets\changes.py", line 34, in __init__
    content = local_changes_file.read_text()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\pathlib.py", line 1257, in read_text
    return f.read()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 127: character maps to <undefined>
2021-09-26 10:55:04 GAMER fastflix-core[6940] DEBUG Conversion worker shutting down`

Please help!

**Comment by cdgriffith** [comment]
Fixed in 4.4.2 - https://github.com/cdgriffith/FastFlix/releases/tag/4.4.2 was due to an encoding error on non-utf-8 systems. Thanks for the report!
