### ISSUE TITLE
FastFlix not running

### ISSUE THREAD

**Issue by dacorsa** [cdgriffith/FastFlix#372]
on latest ubuntu compile from source works well until lanch it:

fastflix-core[3127045] INFO Starting FastFlix 4.10.0
python: symbol lookup error: /app/FastFlix/venv/lib/python3.10/site-packages/PySide2/Qt/plugins/imageformats/libqico.so: undefined symbol: _ZdlPvm, version Qt_5
2022-08-23 13:29:39 NanoKDE fastflix-core[3127045] DEBUG Conversion worker shutting down
python: symbol lookup error: /app/FastFlix/venv/lib/python3.10/site-packages/PySide2/Qt/plugins/imageformats/libqgif.so: undefined symbol: _ZdlPvm, version Qt_5

**Comment by cdgriffith** [comment]
Sorry for delay, I have been away for past month. 

I honestly do not know what the issue is you are having there. [Quick google](https://stackoverflow.com/questions/53022608/application-crashes-with-symbol-zdlpvm-version-qt-5-not-defined-in-file-libqt) says try it may be something with how QT5 was compiled. 

Fastest fix I can think of is to just try out the 5.x branch (git checkout 5.x), make sure using python 3.10 or newer and try building again. It's very much beta branch, but it is using QT6 so at least wouldn't have save issue as before.

**Comment by dacorsa** [comment]
this is the output of 5.x branch

19:18:26 dacorsa@NanoKDE /app/FastFlix 5.x$ python3 -m venv venv
. venv/bin/activate
pip install -r requirements.txt
python -m fastflix
Requirement already satisfied: appdirs~=1.4 in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (1.4.4)
Requirement already satisfied: colorama~=0.4 in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (0.4.5)
Requirement already satisfied: coloredlogs~=15.0 in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (15.0.1)
Requirement already satisfied: iso639-lang==0.0.9 in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (0.0.9)
Requirement already satisfied: mistune~=2.0 in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (2.0.4)
Requirement already satisfied: pathvalidate~=2.4 in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 6)) (2.4.1)
Requirement already satisfied: psutil~=5.9 in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 7)) (5.9.3)
Requirement already satisfied: pydantic~=1.9 in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 8)) (1.10.2)
Requirement already satisfied: PySide6~=6.3 in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 9)) (6.4.0.1)
Requirement already satisfied: python-box[all]~=6.0 in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 10)) (6.0.2)
Requirement already satisfied: requests~=2.28 in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 11)) (2.28.1)
Requirement already satisfied: reusables~=0.9.6 in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 12)) (0.9.6)
Requirement already satisfied: humanfriendly>=9.1 in ./venv/lib/python3.10/site-packages (from coloredlogs~=15.0->-r requirements.txt (line 3)) (10.0)
Requirement already satisfied: typing-extensions>=4.1.0 in ./venv/lib/python3.10/site-packages (from pydantic~=1.9->-r requirements.txt (line 8)) (4.3.0)
Requirement already satisfied: PySide6-Addons==6.4.0.1 in ./venv/lib/python3.10/site-packages (from PySide6~=6.3->-r requirements.txt (line 9)) (6.4.0.1)
Requirement already satisfied: shiboken6==6.4.0.1 in ./venv/lib/python3.10/site-packages (from PySide6~=6.3->-r requirements.txt (line 9)) (6.4.0.1)
Requirement already satisfied: PySide6-Essentials==6.4.0.1 in ./venv/lib/python3.10/site-packages (from PySide6~=6.3->-r requirements.txt (line 9)) (6.4.0.1)
Requirement already satisfied: toml in ./venv/lib/python3.10/site-packages (from python-box[all]~=6.0->-r requirements.txt (line 10)) (0.10.2)
Requirement already satisfied: ruamel.yaml>=0.17 in ./venv/lib/python3.10/site-packages (from python-box[all]~=6.0->-r requirements.txt (line 10)) (0.17.21)
Requirement already satisfied: msgpack in ./venv/lib/python3.10/site-packages (from python-box[all]~=6.0->-r requirements.txt (line 10)) (1.0.4)
Requirement already satisfied: idna<4,>=2.5 in ./venv/lib/python3.10/site-packages (from requests~=2.28->-r requirements.txt (line 11)) (2.10)
Requirement already satisfied: charset-normalizer<3,>=2 in ./venv/lib/python3.10/site-packages (from requests~=2.28->-r requirements.txt (line 11)) (2.1.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./venv/lib/python3.10/site-packages (from requests~=2.28->-r requirements.txt (line 11)) (1.26.12)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.10/site-packages (from requests~=2.28->-r requirements.txt (line 11)) (2022.6.15)
Requirement already satisfied: ruamel.yaml.clib>=0.2.6 in ./venv/lib/python3.10/site-packages (from ruamel.yaml>=0.17->python-box[all]~=6.0->-r requirements.txt (line 10)) (0.2.6)

Traceback (most recent call last):
  File "/app/FastFlix/fastflix/entry.py", line 15, in <module>
    from fastflix.conversion_worker import queue_worker
  File "/app/FastFlix/fastflix/conversion_worker.py", line 13, in <module>
    from fastflix.shared import file_date
  File "/app/FastFlix/fastflix/shared.py", line 28, in <module>
    from PySide6 import QtCore, QtGui, QtWidgets
ImportError: /app/FastFlix/venv/lib/python3.10/site-packages/PySide6/libpyside6.abi3.so.6.4: undefined symbol: _Z5qHash14QByteArrayViewm, version Qt_6
Could not load FastFlix properly!
Please report this issue on https://github.com/cdgriffith/FastFlix/issues (press any key to exit)(venv)

**Comment by dacorsa** [comment]
not works

**Comment by cdgriffith** [comment]
Just making sure, you don't have `LD_LIBRARY_PATH` overwritten anywhere? Like in `.bashrc` or `.profile` ?

What OS is this on?

**Comment by dacorsa** [comment]
Hi

can you tell me what package has :

/app/FastFlix/venv/lib/python3.10/site-packages/PySide6/libpyside6.abi3.so.6.4

thanks

Installing collected packages: reusables, msgpack, mistune, appdirs, urllib3, typing-extensions, toml, shiboken6, ruamel.yaml.clib, python-box, psutil, pathvalidate, iso639-lang, idna, humanfriendly, colorama, charset-normalizer, certifi, ruamel.yaml, requests, PySide6-Essentials, pydantic, coloredlogs, PySide6-Addons, PySide6
Successfully installed PySide6-6.4.0.1 PySide6-Addons-6.4.0.1 PySide6-Essentials-6.4.0.1 appdirs-1.4.4 certifi-2022.9.24 charset-normalizer-2.1.1 colorama-0.4.6 coloredlogs-15.0.1 humanfriendly-10.0 idna-3.4 iso639-lang-0.0.9 mistune-2.0.4 msgpack-1.0.4 pathvalidate-2.5.2 psutil-5.9.4 pydantic-1.10.2 python-box-6.1.0 requests-2.28.1 reusables-0.9.6 ruamel.yaml-0.17.21 ruamel.yaml.clib-0.2.7 shiboken6-6.4.0.1 toml-0.10.2 typing-extensions-4.4.0 urllib3-1.26.12
Traceback (most recent call last):
  File "/app/FastFlix/fastflix/entry.py", line 15, in <module>
    from fastflix.conversion_worker import queue_worker
  File "/app/FastFlix/fastflix/conversion_worker.py", line 13, in <module>
    from fastflix.shared import file_date
  File "/app/FastFlix/fastflix/shared.py", line 28, in <module>
    from PySide6 import QtCore, QtGui, QtWidgets
ImportError: /app/FastFlix/venv/lib/python3.10/site-packages/PySide6/libpyside6.abi3.so.6.4: undefined symbol: _Z5qHash14QByteArrayViewm, version Qt_6
Could not load FastFlix properly!
Please report this issue on https://github.com/cdgriffith/FastFlix/issues (press any key to exit)

**Comment by cdgriffith** [comment]
That's the core GUI package PySide6

I've only see that error on google when that `LD_LIBRARY_PATH` is overwritten,  but I don't know what set it in `/etc/enviroment` if that was system managed or something else modified it.

**Comment by dacorsa** [comment]
can you please upload your working following file:
/app/FastFlix/venv/lib/python3.10/site-packages/PySide6/libpyside6.abi3.so.6.4
Thanks, best regards
