### ISSUE TITLE
osx 13: how to start

### ISSUE THREAD

**Issue by krobipd** [cdgriffith/FastFlix#404]
hello,

I downloaded the osx 12 package, extracted it. downloaded ffmpeg for m1 (https://ffmpeg.martin-riedl.de) and so on.
done the chmod - as you described. after editing the yaml file to find ffmpeg and so on.

I only get this error message. I also tried to manually allow fastfix for file access doesn't help.

> 2023-01-12 13:06:23,946 - fastflix      DEBUG    Using config file fastflix.yaml
2023-01-12 13:06:24,104 - fastflix      INFO     Running command: /Users/krobi/Downloads/FastFlix -version
2023-01-12 13:06:24,115 - fastflix      ERROR    Could not run task Gather FFmpeg version with config version='5.1.0' config_path=PosixPath('fastflix.yaml') ffmpeg=PosixPath('/Users/krobi/Downloads/FastFlix') ffprobe=PosixPath('/Users/krobi/Downloads/FastFlix') hdr10plus_parser=PosixPath('/Users/krobi/Downloads/FastFlix') nvencc=None vceencc=None qsvencc=None output_directory=False source_directory=False output_name_format='{source}-fastflix-{rand_4}.{ext}' flat_ui=True language='eng' logging_level=10 crop_detect_points=10 continue_on_failure=True work_path=PosixPath('/Users/krobi/Downloads/FastFlix') use_sane_audio=True selected_profile='Standard Profile' theme='onyx' disable_version_check=False disable_update_check=False disable_automatic_subtitle_burn_in=False custom_after_run_scripts=Box({}) profiles={'Standard Profile': Profile(profile_version=1, auto_crop=False, keep_aspect_ratio=True, fast_seek=True, rotate=0, vertical_flip=False, horizontal_flip=False, copy_chapters=True, remove_metadata=True, remove_hdr=False, encoder='HEVC (x265)', audio_filters=None, audio_language=None, audio_select=None, audio_select_preferred_language=None, audio_select_first_matching=None, subtitle_language=None, subtitle_select=None, subtitle_select_preferred_language=None, subtitle_automatic_burn_in=None, subtitle_select_first_matching=None, advanced_options=AdvancedOptions(video_speed=1, deblock=None, deblock_size=16, tone_map='hable', vsync=None, brightness=None, saturation=None, contrast=None, maxrate=None, bufsize=None, source_fps=None, output_fps=None, color_space=None, color_transfer=None, color_primaries=None, denoise=None, denoise_type_index=0, denoise_strength_index=0), x265=x265Settings(max_muxing_queue_size='1024', pix_fmt='yuv420p10le', extra='', extra_both_passes=False, preset='medium', intra_encoding=False, profile='default', tune='default', hdr10=False, hdr10_opt=False, dhdr10_opt=False, repeat_headers=False, aq_mode=2, hdr10plus_metadata='', crf=22, bitrate=None, x265_params=[], bframes=4, lossless=False, b_adapt=2, intra_refresh=False, intra_smoothing=True, frame_threads=0, name='HEVC (x265)'), x264=None, rav1e=None, svt_av1=None, svt_av1_avif=None, vp9=None, aom_av1=None, gif=None, webp=None, copy_settings=None, ffmpeg_hevc_nvenc=None, qsvencc_hevc=None, qsvencc_av1=None, qsvencc_avc=None, nvencc_hevc=None, nvencc_avc=None, nvencc_av1=None, vceencc_hevc=None, vceencc_av1=None, vceencc_avc=None, hevc_videotoolbox=None, h264_videotoolbox=None), 'UHD HDR10 Film': Profile(profile_version=1, auto_crop=True, keep_aspect_ratio=True, fast_seek=True, rotate=0, vertical_flip=False, horizontal_flip=False, copy_chapters=True, remove_metadata=True, remove_hdr=False, encoder='HEVC (x265)', audio_filters=None, audio_language=None, audio_select=None, audio_select_preferred_language=None, audio_select_first_matching=None, subtitle_language=None, subtitle_select=None, subtitle_select_preferred_language=None, subtitle_automatic_burn_in=None, subtitle_select_first_matching=None, advanced_options=AdvancedOptions(video_speed=1, deblock=None, deblock_size=16, tone_map='hable', vsync=None, brightness=None, saturation=None, contrast=None, maxrate=None, bufsize=None, source_fps=None, output_fps=None, color_space=None, color_transfer=None, color_primaries=None, denoise=None, denoise_type_index=0, denoise_strength_index=0), x265=x265Settings(max_muxing_queue_size='1024', pix_fmt='yuv420p10le', extra='', extra_both_passes=False, preset='slow', intra_encoding=False, profile='default', tune='default', hdr10=True, hdr10_opt=True, dhdr10_opt=False, repeat_headers=True, aq_mode=2, hdr10plus_metadata='', crf=18, bitrate=None, x265_params=[], bframes=4, lossless=False, b_adapt=2, intra_refresh=False, intra_smoothing=True, frame_threads=0, name='HEVC (x265)'), x264=None, rav1e=None, svt_av1=None, svt_av1_avif=None, vp9=None, aom_av1=None, gif=None, webp=None, copy_settings=None, ffmpeg_hevc_nvenc=None, qsvencc_hevc=None, qsvencc_av1=None, qsvencc_avc=None, nvencc_hevc=None, nvencc_avc=None, nvencc_av1=None, vceencc_hevc=None, vceencc_av1=None, vceencc_avc=None, hevc_videotoolbox=None, h264_videotoolbox=None), '1080p Film': Profile(profile_version=1, auto_crop=True, keep_aspect_ratio=True, fast_seek=True, rotate=0, vertical_flip=False, horizontal_flip=False, copy_chapters=True, remove_metadata=True, remove_hdr=False, encoder='AVC (x264)', audio_filters=None, audio_language=None, audio_select=None, audio_select_preferred_language=None, audio_select_first_matching=None, subtitle_language=None, subtitle_select=None, subtitle_select_preferred_language=None, subtitle_automatic_burn_in=None, subtitle_select_first_matching=None, advanced_options=AdvancedOptions(video_speed=1, deblock=None, deblock_size=16, tone_map='hable', vsync=None, brightness=None, saturation=None, contrast=None, maxrate=None, bufsize=None, source_fps=None, output_fps=None, color_space=None, color_transfer=None, color_primaries=None, denoise=None, denoise_type_index=0, denoise_strength_index=0), x265=None, x264=x264Settings(max_muxing_queue_size='1024', pix_fmt='yuv420p', extra='', extra_both_passes=False, preset='slow', profile='default', tune=None, crf=22, bitrate=None, name='AVC (x264)'), rav1e=None, svt_av1=None, svt_av1_avif=None, vp9=None, aom_av1=None, gif=None, webp=None, copy_settings=None, ffmpeg_hevc_nvenc=None, qsvencc_hevc=None, qsvencc_av1=None, qsvencc_avc=None, nvencc_hevc=None, nvencc_avc=None, nvencc_av1=None, vceencc_hevc=None, vceencc_av1=None, vceencc_avc=None, hevc_videotoolbox=None, h264_videotoolbox=None)} priority='Normal' stay_on_top=False portable_mode=False sane_audio_selection=BoxList(['aac', 'ac3', 'alac', 'dca', 'dts', 'eac3', 'flac', 'libfdk_aac', 'libmp3lame', 'libopus', 'libvorbis', 'libwavpack', 'snoicls', 'sonic', 'truehd', 'tta'])
Traceback (most recent call last):
  File "fastflix/widgets/progress_bar.py", line 92, in run
    task.command(config=self.app.fastflix.config, app=self.app, **task.kwargs)
  File "fastflix/flix.py", line 154, in ffmpeg_configuration
    res = execute([f"{config.ffmpeg}", "-version"])
  File "fastflix/flix.py", line 141, in execute
    return run(
  File "subprocess.py", line 503, in run
  File "subprocess.py", line 971, in __init__
  File "subprocess.py", line 1847, in _execute_child
PermissionError: [Errno 13] Permission denied: '/Users/krobi/Downloads/FastFlix'
2023-01-12 13:06:24,117 - fastflix      ERROR    Exception in 'run': [Errno 13] Permission denied: '/Users/krobi/Downloads/FastFlix' - args: (<fastflix.widgets.progress_bar.ProgressBar(0x600002344ba0, name="ProgressBar") at 0x120182480>,)
Traceback (most recent call last):
  File "reusables/wrappers.py", line 285, in wrapper
  File "fastflix/widgets/progress_bar.py", line 92, in run
    task.command(config=self.app.fastflix.config, app=self.app, **task.kwargs)
  File "fastflix/flix.py", line 154, in ffmpeg_configuration
    res = execute([f"{config.ffmpeg}", "-version"])
  File "fastflix/flix.py", line 141, in execute
    return run(
  File "subprocess.py", line 503, in run
  File "subprocess.py", line 971, in __init__
  File "subprocess.py", line 1847, in _execute_child
PermissionError: [Errno 13] Permission denied: '/Users/krobi/Downloads/FastFlix'
2023-01-12 13:06:24,117 - fastflix      ERROR    Could not start FastFlix!
Traceback (most recent call last):
  File "fastflix/application.py", line 200, in start_app
    ProgressBar(app, startup_tasks)
  File "fastflix/widgets/progress_bar.py", line 61, in __init__
    self.run()
  File "reusables/wrappers.py", line 293, in wrapper
  File "reusables/wrappers.py", line 285, in wrapper
  File "fastflix/widgets/progress_bar.py", line 92, in run
    task.command(config=self.app.fastflix.config, app=self.app, **task.kwargs)
  File "fastflix/flix.py", line 154, in ffmpeg_configuration
    res = execute([f"{config.ffmpeg}", "-version"])
  File "fastflix/flix.py", line 141, in execute
    return run(
  File "subprocess.py", line 503, in run
  File "subprocess.py", line 971, in __init__
  File "subprocess.py", line 1847, in _execute_child
PermissionError: [Errno 13] Permission denied: '/Users/krobi/Downloads/FastFlix'

**Comment by cdgriffith** [comment]
Apologizes for delay, totally missed this issue apparently! 

It seems that you have the `ffmpeg` path set to `FastFlix` instead of an `ffmpeg` executable.
