### ISSUE TITLE
No module named 'psutil._psutil_windows'

### ISSUE THREAD

**Issue by vodka1998** [cdgriffith/FastFlix#406]
pip install -r requirements.txt
Successfully installed PySide6-6.4.2 PySide6-Addons-6.4.2 PySide6-Essentials-6.4.2 appdirs-1.4.4 coloredlogs-15.0.1 humanfriendly-10.0 iso639-lang-0.0.9 msgpack-1.0.4 pathvalidate-2.5.2 pydantic-1.10.4 pyreadline3-3.4.1 python-box-6.1.0 requests-2.28.2 reusables-0.9.6 ruamel.yaml-0.17.21 shiboken6-6.4.2 typing-extensions-4.4.0

python -m fastflix
Traceback (most recent call last):
  File "D:\git\FastFlix\fastflix\entry.py", line 15, in <module>
    from fastflix.conversion_worker import queue_worker
  File "D:\git\FastFlix\fastflix\conversion_worker.py", line 11, in <module>
    from fastflix.command_runner import BackgroundRunner
  File "D:\git\FastFlix\fastflix\command_runner.py", line 12, in <module>
    from psutil import Popen
  File "D:\Python\Lib\site-packages\psutil\__init__.py", line 109, in <module>
    from . import _pswindows as _psplatform
  File "D:\Python\Lib\site-packages\psutil\_pswindows.py", line 35, in <module>
    from ._psutil_windows import ABOVE_NORMAL_PRIORITY_CLASS
ModuleNotFoundError: No module named 'psutil._psutil_windows'
Could not load FastFlix properly!
Please report this issue on https://github.com/cdgriffith/FastFlix/issues (press any key to exit)

win11 22621
pthon 3.11 

pip uninstall psutil
find "psutil-5.9.0-cp311-cp311-win_amd64.whl"
pip install psutil-5.9.0-cp311-cp311-win_amd64.whl

it seems solved

**Comment by plhvlogs** [comment]
in windows, i think u use GUI instead, it easier for use

**Comment by cdgriffith** [comment]
Hi @plhvlogs , Yes I recommend using the `exe` file in the [release](https://github.com/cdgriffith/FastFlix/releases) on Windows. I would only try building yourself if you want to work on writing code for FastFlix. 

Also as of 5.2.0 I have moved away from the standard `pip` install and now use `poetry` to hopefully resolve any dependency issues like you experienced!

**Comment by cdgriffith** [comment]
Moved back from poetry to setuptools, but using newer pyproject.toml file. Now how to run from source is listed in the release. https://github.com/cdgriffith/FastFlix/releases/tag/5.5.3  Please do let me know if you have further issues!
