### ISSUE TITLE
HDR10+ Extract Broken?

### ISSUE THREAD

**Issue by mrdav1** [cdgriffith/FastFlix#421]
I am running FastFlix 5.1.0 on Windows 10 and when I try to extract HDR10+ metadata the following error occurs:

_2023-03-04 12:17:31 Study fastflix[13212] INFO Generating thumbnail: "C:\Users\Maddie\AppData\Roaming\FFmpeg\bin\ffmpeg.exe" -ss 159.28 -loglevel warning -i "D:\Users\Maddie\Videos\To Master\TV\05 Servant (2160p WEB CAKES)\08 Tunnels (2160p HD).mkv" -init_hw_device opencl=ocl -filter_hw_device ocl  -filter_complex "[0:0]format=p010,hwupload,tonemap_opencl=tonemap=hable:desat=0:r=tv:p=bt709:t=bt709:m=bt709:format=nv12,hwdownload,format=nv12,scale='min(440\,iw):-8'[v]" -map "[v]"   -an -y -map_metadata -1 -frames:v 1 "D:\Users\Maddie\AppData\Roaming\FastFlix\thumbnail_preview.jpg"
2023-03-04 12:18:07 Study fastflix[13212] INFO Extracting HDR10+ metadata to D:\Users\Maddie\AppData\Roaming\FastFlix\temp_f256862e71906b33be11d721\metadata.json
2023-03-04 12:18:07 Study fastflix[13212] WARNING Using HDR10 parser version 1.6.0
2023-03-04 12:18:07 Study fastflix[13212] WARNING Running command: C:\Users\Maddie\AppData\Roaming\FFmpeg\bin\ffmpeg.exe -y -i D:\Users\Maddie\Videos\To Master\TV\05 Servant (2160p WEB CAKES)\08 Tunnels (2160p HD).mkv -map 0:0 -c:v copy -vbsf hevc_mp4toannexb -f hevc - | C:\Users\Maddie\AppData\Roaming\FFmpeg\bin\hdr10plus_tool.exe extract -o D:\Users\Maddie\AppData\Roaming\FastFlix\temp_f256862e71906b33be11d721\metadata.json -
Traceback (most recent call last):
  File "fastflix\widgets\background_tasks.py", line 165, in run
    if line := f.readline().rstrip():
  File "codecs.py", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 0-1: unexpected end of data_ 

This has worked OK in the past.

Please help.

**Comment by mrdav1** [comment]
Update: I managed to get it to work by doing some housekeeping.  I deleted hundreds of empty folders in "D:\Users\Maddie\AppData\Roaming\FastFlix\" (I guess they're left for previous encodes?) and now it all works OK.

**Comment by cdgriffith** [comment]
Thanks for the update, I will see what I can do for better cleanup!

**Comment by mrdav1** [comment]
That would be greatly appreciated.  I've just found that "...\AppData\Roaming\FastFlix\queue_extras" contains over 15,000 files equalling 2TB of old metadata!

**Comment by cdgriffith** [comment]
Automatic cleanup now in [5.2.0](https://github.com/cdgriffith/FastFlix/releases/tag/5.2.0)!
