### ISSUE TITLE
Error when dropping mkv into FastFlix.

### ISSUE THREAD

**Issue by mrdav1** [cdgriffith/FastFlix#427]
Using FastFlix 5.2.0 on Winows 10 and I am unable to drop an mkv file into window

Exverything was fine in 5.1.0 but I'm now seeing the following when dropping!

_2023-03-09 18:57:01 Study fastflix[17000] INFO Running command: C:\Users\Maddie\AppData\Roaming\FFmpeg\bin\ffprobe.exe -v quiet -loglevel panic -print_format json -show_format -show_streams D:\Users\Maddie\Videos\To Master\TV\00 History Of The World Part II (2160p WEB GGEZ)\07 VII (2160p HD).mkv
2023-03-09 18:57:01 Study fastflix[17000] INFO Running command: C:\Users\Maddie\AppData\Roaming\FFmpeg\bin\ffmpeg.exe -hide_banner -i D:\Users\Maddie\Videos\To Master\TV\00 History Of The World Part II (2160p WEB GGEZ)\07 VII (2160p HD).mkv -vf idet -frames:v 100 -an -sn -dn -f rawvideo NUL -y
2023-03-09 18:57:04 Study fastflix[17000] INFO Running command: C:\Users\Maddie\AppData\Roaming\FFmpeg\bin\ffprobe.exe -loglevel panic -select_streams 0 -print_format json -show_frames -read_intervals %+#1 -show_entries frame=color_space,color_primaries,color_transfer,side_data_list,pix_fmt D:\Users\Maddie\Videos\To Master\TV\00 History Of The World Part II (2160p WEB GGEZ)\07 VII (2160p HD).mkv
2023-03-09 18:57:04 Study fastflix[17000] DEBUG Using HDR10 parser version 1.6.0
2023-03-09 18:57:04 Study fastflix[17000] DEBUG Checking for hdr10+ in stream 0
2023-03-09 18:57:04 Study fastflix[17000] DEBUG 1 video tracks found
2023-03-09 18:57:04 Study fastflix[17000] DEBUG 1 audio tracks found
2023-03-09 18:57:04 Study fastflix[17000] DEBUG 2 subtitle tracks found
2023-03-09 18:57:04 Study fastflix[17000] ERROR Exception in 'update_video_info': 'BoxList' object has no attribute 'items' - args: (<fastflix.widgets.main.Main(0x22027332d00, name="Main") at 0x000002202B2D29C0>,)
2023-03-09 18:57:04 Study fastflix[17000] ERROR Could not load video D:\Users\Maddie\Videos\To Master\TV\00 History Of The World Part II (2160p WEB GGEZ)\07 VII (2160p HD).mkv
Traceback (most recent call last):
  File "fastflix\widgets\main.py", line 1938, in dropEvent
    self.update_video_info()
  File "reusables\wrappers.py", line 293, in wrapper
  File "reusables\wrappers.py", line 285, in wrapper
  File "fastflix\widgets\main.py", line 1503, in update_video_info
    for k, v in self.app.fastflix.current_video.streams.video[0].get("tags", []).items()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BoxList' object has no attribute 'items'_

Please help

**Comment by cdgriffith** [comment]
Thank you for letting me know of this issue, hopefully fixed in https://github.com/cdgriffith/FastFlix/releases/tag/5.2.1

**Comment by mrdav1** [comment]
Sorted now... thanks
