### ISSUE TITLE
RuntimeError: Internal C++ object (AudioProfile) already deleted

### ISSUE THREAD

**Issue by jfroy** [cdgriffith/FastFlix#466]
**FastFlix Version:**
5.5.0

**Operating System:**
Windows 11 Pro 22H2 (22621.1555)

**Describe the bug**
I get an exception when trying to add an audio track pattern match in a profile.

**To Reproduce**
- Open a media file (in my case, an mkv with one video track and 2 audio track (2 different language).
- Select Profiles > New Profiles from the menu.
- Under Audio, de-select Passthrough All, then click on Add Pattern Match.

**Screenshots**

**Logs**

```
Traceback (most recent call last):
  File "fastflix\widgets\windows\profile_window.py", line 202, in add_track
    self.tracks.append(AudioProfile(self, self.app, self.main, self.inner_widget, len(self.tracks)))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "fastflix\widgets\windows\profile_window.py", line 109, in __init__
    self.setLayout(self.grid)
RuntimeError: Internal C++ object (AudioProfile) already deleted.
```

**Comment by jfroy** [comment]
> I was able to recreate this on windows using the installer version (not having that issue with running code directly of course, so more fun to debug!)

Yeah I'm using the installer version. It doesn't always reproduce, but it's pretty consistent when starting from a clean slate, opening a media file, and trying to setup audio track patterns.

**Comment by cdgriffith** [comment]
Hopefully fixed in 5.5.1 https://github.com/cdgriffith/FastFlix/releases/tag/5.5.1 thanks for report!
