### ISSUE TITLE
Can't make NVEncC get working

### ISSUE THREAD

**Issue by suphamster** [cdgriffith/FastFlix#490]
**FastFlix Version:**
5.5.5 (both portable and not)
**Operating System:**
Windows 10 22H2 x64, Administrator account, UAC disabled. GPU RTX 4070. NVEncC separately (without FastFlix) works fine.

**Describe the bug**
 NVEncC not working

**To Reproduce**
Add folder path to NVEncC in settings and restart FastFlix

**Logs** (If applicable) In FastFlix you can go to Help > Open Log Directory and sort by latest to find the newest log file to add here.
```
2023-05-25 17:18:54 DESKTOP fastflix-core[11936] INFO Starting FastFlix 5.5.5
2023-05-25 17:19:00 DESKTOP fastflix[2828] DEBUG Using config file fastflix.yaml
2023-05-25 17:19:00 DESKTOP fastflix[2828] INFO Checking for available NVEncC encoders
2023-05-25 17:19:00 DESKTOP fastflix[2828] ERROR Errored while checking for available NVEncC formats
Traceback (most recent call last):
  File "fastflix\models\config.py", line 330, in check_hw_encoders
    self.nvencc_devices, self.nvencc_encoders = get_all_encoder_formats_and_devices(
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "fastflix\rigaya_helpers.py", line 90, in get_all_encoder_formats_and_devices
    for output in run_check_features(executable=executable, is_qsv=is_qsv):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "fastflix\rigaya_helpers.py", line 79, in run_check_features
    result = run([executable, "--check-features", str(i)], stdout=PIPE, stderr=PIPE, encoding="utf-8")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "subprocess.py", line 548, in run
  File "subprocess.py", line 1024, in __init__
  File "subprocess.py", line 1509, in _execute_child
PermissionError: [WinError 5]
```

**Comment by cdgriffith** [comment]
Odd that it is a permissions error. Is the NVEncC folder on another drive or shared drive?

**Comment by suphamster** [comment]
Maybe I was just dumb, sry to bother but I didn't know that I need pack to exe file exactly not just folder so I've manually pasted path to NVEncC but I needed to press yellow button where it asked me for exe location.
