### ISSUE TITLE
Not is possible start Fastflix even with ffmpeg 4

### ISSUE THREAD

**Issue by Augusto7743** [cdgriffith/FastFlix#540]
Hello.
Thanks for reading my topic.

Here Ubuntu 20.04.6. Nvidia driver 470. ffmpeg 4.4.2.
FastFlix current version 5.6

when I try to load fastflix in command line ./fastflix not start the programa, but show error lines

2024-01-12 05:34:36 A1 fastflix-core[1798668] INFO Starting FastFlix 5.6.0
2024-01-12 05:34:37 A1 fastflix[1798728] DEBUG Using config file /home/username/.local/share/FastFlix/fastflix.yaml
2024-01-12 05:34:37 A1 fastflix[1798728] INFO Running command: /usr/bin/ffmpeg -version
2024-01-12 05:34:38 A1 fastflix[1798728] ERROR /usr/bin/ffmpeg command stdout: 
2024-01-12 05:34:38 A1 fastflix[1798728] ERROR /usr/bin/ffmpeg command stderr: /usr/bin/ffmpeg: symbol lookup error: /lib/x86_64-linux-gnu/libdecor-0.so.0: undefined symbol: wl_proxy_marshal_flags

2024-01-12 05:34:38 A1 fastflix[1798728] ERROR Could not run task Gather FFmpeg version with config version='5.6.0' config_path=PosixPath('/home/username/.local/share/FastFlix/fastflix.yaml') ffmpeg=PosixPath('/usr/bin/ffmpeg') ffprobe=PosixPath('/usr/bin/ffprobe') hdr10plus_parser=None nvencc=None vceencc=None qsvencc=None output_directory=False source_directory=False output_name_format='{source}-fastflix-{rand_4}' flat_ui=True language='eng' logging_level=10 crop_detect_points=10 continue_on_failure=True work_path=PosixPath('/home/username/.local/share/FastFlix') use_sane_audio=True selected_profile='Standard Profile' theme='onyx' disable_version_check=True disable_update_check=True disable_automatic_subtitle_burn_in=False custom_after_run_scripts=Box({}) profiles={'Standard Profile': Profile(profile_version=1, auto_crop=False, fast_seek=True, rotate=0, vertical_flip=False, horizontal_flip=False, copy_chapters=True, remove_metadata=True, remove_hdr=False, encoder='HEVC (x265)', resolution_method='auto', resolution_custom=None, output_type='.mkv', audio_filters=None, audio_language=None, audio_select=None, audio_select_preferred_language=None, audio_select_first_matching=None, subtitle_language=None, subtitle_select=None, subtitle_select_preferred_language=None, subtitle_automatic_burn_in=None, subtitle_select_first_matching=None, advanced_options=AdvancedOptions(video_speed=1, deblock=None, deblock_size=16, tone_map='hable', vsync=None, brightness=None, saturation=None, contrast=None, maxrate=None, bufsize=None, source_fps=None, output_fps=None, color_space=None, color_transfer=None, color_primaries=None, denoise=None, denoise_type_index=0, denoise_strength_index=0), x265=x265Settings(max_muxing_queue_size='1024', pix_fmt='yuv420p10le', extra='', extra_both_passes=False, preset='medium', intra_encoding=False, profile='default', tune='default', hdr10=False, hdr10_opt=False, dhdr10_opt=False, repeat_headers=False, aq_mode=2, hdr10plus_metadata='', crf=22, bitrate=None, x265_params=[], bframes=4, lossless=False, b_adapt=2, intra_refresh=False, intra_smoothing=True, frame_threads=0, bitrate_passes=2, name='HEVC (x265)'), vvc=None, x264=None, rav1e=None, svt_av1=None, svt_av1_avif=None, vp9=None, aom_av1=None, gif=None, webp=None, copy_settings=None, ffmpeg_hevc_nvenc=None, qsvencc_hevc=None, qsvencc_av1=None, qsvencc_avc=None, nvencc_hevc=None, nvencc_avc=None, nvencc_av1=None, vceencc_hevc=None, vceencc_av1=None, vceencc_avc=None, hevc_videotoolbox=None, h264_videotoolbox=None, vaapi_h264=None, vaapi_hevc=None, vaapi_vp9=None, vaapi_mpeg2=None), 'UHD HDR10 Film': Profile(profile_version=1, auto_crop=True, fast_seek=True, rotate=0, vertical_flip=False, horizontal_flip=False, copy_chapters=True, remove_metadata=True, remove_hdr=False, encoder='HEVC (x265)', resolution_method='auto', resolution_custom=None, output_type='.mkv', audio_filters=None, audio_language=None, audio_select=None, audio_select_preferred_language=None, audio_select_first_matching=None, subtitle_language=None, subtitle_select=None, subtitle_select_preferred_language=None, subtitle_automatic_burn_in=None, subtitle_select_first_matching=None, advanced_options=AdvancedOptions(video_speed=1, deblock=None, deblock_size=16, tone_map='hable', vsync=None, brightness=None, saturation=None, contrast=None, maxrate=None, bufsize=None, source_fps=None, output_fps=None, color_space=None, color_transfer=None, color_primaries=None, denoise=None, denoise_type_index=0, denoise_strength_index=0), x265=x265Settings(max_muxing_queue_size='1024', pix_fmt='yuv420p10le', extra='', extra_both_passes=False, preset='slow', intra_encoding=False, profile='default', tune='default', hdr10=True, hdr10_opt=True, dhdr10_opt=False, repeat_headers=True, aq_mode=2, hdr10plus_metadata='', crf=18, bitrate=None, x265_params=[], bframes=4, lossless=False, b_adapt=2, intra_refresh=False, intra_smoothing=True, frame_threads=0, bitrate_passes=2, name='HEVC (x265)'), vvc=None, x264=None, rav1e=None, svt_av1=None, svt_av1_avif=None, vp9=None, aom_av1=None, gif=None, webp=None, copy_settings=None, ffmpeg_hevc_nvenc=None, qsvencc_hevc=None, qsvencc_av1=None, qsvencc_avc=None, nvencc_hevc=None, nvencc_avc=None, nvencc_av1=None, vceencc_hevc=None, vceencc_av1=None, vceencc_avc=None, hevc_videotoolbox=None, h264_videotoolbox=None, vaapi_h264=None, vaapi_hevc=None, vaapi_vp9=None, vaapi_mpeg2=None), '1080p Film': Profile(profile_version=1, auto_crop=True, fast_seek=True, rotate=0, vertical_flip=False, horizontal_flip=False, copy_chapters=True, remove_metadata=True, remove_hdr=False, encoder='AVC (x264)', resolution_method='auto', resolution_custom=None, output_type='.mkv', audio_filters=None, audio_language=None, audio_select=None, audio_select_preferred_language=None, audio_select_first_matching=None, subtitle_language=None, subtitle_select=None, subtitle_select_preferred_language=None, subtitle_automatic_burn_in=None, subtitle_select_first_matching=None, advanced_options=AdvancedOptions(video_speed=1, deblock=None, deblock_size=16, tone_map='hable', vsync=None, brightness=None, saturation=None, contrast=None, maxrate=None, bufsize=None, source_fps=None, output_fps=None, color_space=None, color_transfer=None, color_primaries=None, denoise=None, denoise_type_index=0, denoise_strength_index=0), x265=None, vvc=None, x264=x264Settings(max_muxing_queue_size='1024', pix_fmt='yuv420p', extra='', extra_both_passes=False, preset='slow', profile='default', tune=None, crf=22, bitrate=None, bitrate_passes=2, name='AVC (x264)'), rav1e=None, svt_av1=None, svt_av1_avif=None, vp9=None, aom_av1=None, gif=None, webp=None, copy_settings=None, ffmpeg_hevc_nvenc=None, qsvencc_hevc=None, qsvencc_av1=None, qsvencc_avc=None, nvencc_hevc=None, nvencc_avc=None, nvencc_av1=None, vceencc_hevc=None, vceencc_av1=None, vceencc_avc=None, hevc_videotoolbox=None, h264_videotoolbox=None, vaapi_h264=None, vaapi_hevc=None, vaapi_vp9=None, vaapi_mpeg2=None)} priority='Normal' stay_on_top=False portable_mode=False ui_scale='1' clean_old_logs=True sane_audio_selection=BoxList(['aac', 'ac3', 'alac', 'dca', 'dts', 'eac3', 'flac', 'libfdk_aac', 'libmp3lame', 'libopus', 'libvorbis', 'libwavpack', 'snoicls', 'sonic', 'truehd', 'tta']) vceencc_encoders=[] qsvencc_encoders=[] nvencc_encoders=[] vceencc_devices=Box({}) qsvencc_devices=Box({}) nvencc_devices=Box({}) sticky_tabs=False disable_complete_message=False
Traceback (most recent call last):
  File "fastflix/widgets/progress_bar.py", line 94, in run
    task.command(config=self.app.fastflix.config, app=self.app, **task.kwargs)                                                                                                                                    
  File "fastflix/flix.py", line 158, in ffmpeg_configuration                                                                                                                                                      
    raise FlixError(f'"{config.ffmpeg}" file not found or errored while executing. Return code {res.returncode}')                                                                                                 
fastflix.exceptions.FlixError: "/usr/bin/ffmpeg" file not found or errored while executing. Return code 127                                                                                                       
2024-01-12 05:34:38 A1 fastflix[1798728] ERROR Exception in 'run': "/usr/bin/ffmpeg" file not found or errored while executing. Return code 127 - args: (<fastflix.widgets.progress_bar.ProgressBar(0x2e1bc80, name="ProgressBar") at 0x79df1b042700>,)                                                                                                                                                                             
Traceback (most recent call last):                                                                                                                                                                                
  File "reusables/wrappers.py", line 285, in wrapper                                                                                                                                                              
  File "fastflix/widgets/progress_bar.py", line 94, in run                                                                                                                                                        
    task.command(config=self.app.fastflix.config, app=self.app, **task.kwargs)                                                                                                                                    
  File "fastflix/flix.py", line 158, in ffmpeg_configuration
    raise FlixError(f'"{config.ffmpeg}" file not found or errored while executing. Return code {res.returncode}')
fastflix.exceptions.FlixError: "/usr/bin/ffmpeg" file not found or errored while executing. Return code 127
2024-01-12 05:34:38 A1 fastflix[1798728] ERROR Could not start FastFlix!
Traceback (most recent call last):
  File "fastflix/application.py", line 228, in app_setup
    ProgressBar(app, startup_tasks)
  File "fastflix/widgets/progress_bar.py", line 63, in __init__
    self.run()
  File "reusables/wrappers.py", line 293, in wrapper
  File "reusables/wrappers.py", line 285, in wrapper
  File "fastflix/widgets/progress_bar.py", line 94, in run
    task.command(config=self.app.fastflix.config, app=self.app, **task.kwargs)
  File "fastflix/flix.py", line 158, in ffmpeg_configuration
    raise FlixError(f'"{config.ffmpeg}" file not found or errored while executing. Return code {res.returncode}')
fastflix.exceptions.FlixError: "/usr/bin/ffmpeg" file not found or errored while executing. Return code 127
2024-01-12 05:34:38 A1 fastflix-core[1798668] DEBUG Conversion worker shutting down

ffmpeg run correctly in others softwares even with nvenc acceleration.

Any help ?
Have an nice day.

**Comment by cdgriffith** [comment]
Well totally missed asking for other details for this 2 years ago, my apologies! If you are still having that issue or even remember what FastFlix is, sorry for the delay and happy to help out however possible!
