### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by mikeSGman** [cdgriffith/FastFlix#571]
**FastFlix Version:** 5.7.1

**Operating System:** Windows 11

**Describe the bug:** When attempting to set the audio conversion to aac, an error appears in the console:

```Traceback (most recent call last):
  File "fastflix\widgets\windows\audio_conversion.py", line 204, in save
  File "fastflix\widgets\panels\audio_panel.py", line 203, in page_update
  File "fastflix\widgets\main.py", line 1804, in page_update
  File "fastflix\widgets\main.py", line 1755, in build_commands
  File "fastflix\encoders\ffmpeg_hevc_nvenc\command_builder.py", line 13, in build
  File "fastflix\encoders\common\helpers.py", line 253, in generate_all
  File "fastflix\encoders\common\audio.py", line 59, in build_audio
AttributeError: 'NoneType' object has no attribute 'lower'
```

ffmpeg has been updated via the dropdown selector, in the interface:

```ffmpeg -version
ffmpeg version 2024-04-18-git-35ae44c615-full_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers
built with gcc 13.2.0 (Rev5, Built by MSYS2 project)
configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libxevd --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxeve --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-ffnvcodec --enable-libvpl --enable-nvdec --enable-nvenc --enable-vaapi --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
libavutil      59. 15.100 / 59. 15.100
libavcodec     61.  5.103 / 61.  5.103
libavformat    61.  3.100 / 61.  3.100
libavdevice    61.  2.100 / 61.  2.100
libavfilter    10.  2.101 / 10.  2.101
libswscale      8.  2.100 /  8.  2.100
libswresample   5.  2.100 /  5.  2.100
libpostproc    58.  2.100 / 58.  2.100
```

![image](https://github.com/cdgriffith/FastFlix/assets/398394/1a5cf5f9-5c43-417c-867b-544171736e63)

**Comment by mikeSGman** [comment]
I used the built-in ffmpeg NVENC for the OP and the above screenshots. Since this post, I downloaded Rigaya's NVEncC and linked the executable to the binary via the GUI. It appears the str.lower error went away: I'm attempting a conversion with an AAC transcode on the same source and will report back here afterward. So far, it's looking promising.

**Comment by mikeSGman** [comment]
I confirmed that it works by using Rigaya's NVEncC. @cdgriffith I see you've [tagged a fix](https://github.com/cdgriffith/FastFlix/commit/7cc806b373c10153553817d2073fca5ce8d89290) already, thanks!!

**Comment by cdgriffith** [comment]
Thanks for the report! Fixed https://github.com/cdgriffith/FastFlix/releases/tag/5.7.2 hopefully
