### ISSUE TITLE
FastFlix fails to launch on Nobara40, version `GLIBCXX_3.4.32' not found

### ISSUE THREAD

**Issue by BuyMyMojo** [cdgriffith/FastFlix#609]
**FastFlix Version:** 5.8.1

**Operating System:** Nobara Linux 40

**Describe the bug**
FastFlix fails to launch and complains about missing FFMPEG because of it.

**To Reproduce**
Run on the latest version of Nobara Linux with ffmpeg installed

**Logs**
CLI output:
```sh
buymymojo@nobara-pc:~/Downloads/FastFlix_5.8.1_ubuntu-22.04_x86_64$ ./FastFlix
2024-09-14 19:59:25 nobara-pc fastflix-core[83854] INFO Starting FastFlix 5.8.1
2024-09-14 19:59:25 nobara-pc fastflix[83861] DEBUG Using config file /home/buymymojo/.local/share/FastFlix/fastflix.yaml
qt.qpa.wayland: EGL not available
2024-09-14 19:59:25 nobara-pc fastflix[83861] INFO Running task Gather FFmpeg version
2024-09-14 19:59:25 nobara-pc fastflix[83861] INFO Running command: /usr/bin/ffmpeg -version
2024-09-14 19:59:25 nobara-pc fastflix[83861] ERROR /usr/bin/ffmpeg command stdout: 
2024-09-14 19:59:25 nobara-pc fastflix[83861] ERROR /usr/bin/ffmpeg command stderr: /usr/bin/ffmpeg: /tmp/_MEIMBQFvy/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /lib64/libjack.so.0)
/usr/bin/ffmpeg: /tmp/_MEIMBQFvy/libstdc++.so.6: version `CXXABI_1.3.15' not found (required by /lib64/libjack.so.0)
/usr/bin/ffmpeg: /tmp/_MEIMBQFvy/libstdc++.so.6: version `CXXABI_1.3.15' not found (required by /lib64/libopenal.so.1)
/usr/bin/ffmpeg: /tmp/_MEIMBQFvy/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /lib64/librubberband.so.2)
/usr/bin/ffmpeg: /tmp/_MEIMBQFvy/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /lib64/libtesseract.so.5.3.4)
/usr/bin/ffmpeg: /tmp/_MEIMBQFvy/libstdc++.so.6: version `CXXABI_1.3.15' not found (required by /lib64/libzimg.so.2)
/usr/bin/ffmpeg: /tmp/_MEIMBQFvy/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /lib64/libshaderc_shared.so.1)
/usr/bin/ffmpeg: /tmp/_MEIMBQFvy/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /lib64/libopenmpt.so.0)
/usr/bin/ffmpeg: /tmp/_MEIMBQFvy/libstdc++.so.6: version `CXXABI_1.3.15' not found (required by /lib64/libvapoursynth-script.so.0)
/usr/bin/ffmpeg: /tmp/_MEIMBQFvy/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /lib64/libchromaprint.so.1)
/usr/bin/ffmpeg: /tmp/_MEIMBQFvy/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /lib64/libsrt.so.1.5)
/usr/bin/ffmpeg: /tmp/_MEIMBQFvy/libstdc++.so.6: version `CXXABI_1.3.15' not found (required by /lib64/libsrt.so.1.5)
/usr/bin/ffmpeg: /tmp/_MEIMBQFvy/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /lib64/libx265.so.209)
/usr/bin/ffmpeg: /tmp/_MEIMBQFvy/libssl.so.3: version `OPENSSL_3.2.0' not found (required by /lib64/libcurl.so.4)
/usr/bin/ffmpeg: /tmp/_MEIMBQFvy/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /lib64/libSPIRV-Tools.so)
/usr/bin/ffmpeg: /tmp/_MEIMBQFvy/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /lib64/libSPIRV-Tools-opt.so)

2024-09-14 19:59:25 nobara-pc fastflix[83861] ERROR Could not run task Gather FFmpeg version with config version='5.8.1' config_path=PosixPath('/home/buymymojo/.local/share/FastFlix/fastflix.yaml') ffmpeg=PosixPath('/usr/bin/ffmpeg') ffprobe=PosixPath('/usr/bin/ffprobe') hdr10plus_parser=None nvencc=None vceencc=None qsvencc=None output_directory=False source_directory=False output_name_format='{source}-fastflix-{rand_4}' flat_ui=True language='eng' logging_level=10 crop_detect_points=10 continue_on_failure=True work_path=PosixPath('/home/buymymojo/.local/share/FastFlix') use_sane_audio=True selected_profile='Standard Profile' theme='onyx' disable_version_check=False disable_update_check=False disable_automatic_subtitle_burn_in=False custom_after_run_scripts=Box({}) profiles={'Standard Profile': Profile(profile_version=1, auto_crop=False, fast_seek=True, rotate=0, vertical_flip=False, horizontal_flip=False, copy_chapters=True, remove_metadata=True, remove_hdr=False, encoder='HEVC (x265)', resolution_method='auto', resolution_custom=None, output_type='.mkv', audio_filters=None, audio_language=None, audio_select=None, audio_select_preferred_language=None, audio_select_first_matching=None, subtitle_language=None, subtitle_select=None, subtitle_select_preferred_language=None, subtitle_automatic_burn_in=None, subtitle_select_first_matching=None, advanced_options=AdvancedOptions(video_speed=1, deblock=None, deblock_size=16, tone_map='hable', vsync=None, brightness=None, saturation=None, contrast=None, maxrate=None, bufsize=None, source_fps=None, output_fps=None, color_space=None, color_transfer=None, color_primaries=None, denoise=None, denoise_type_index=0, denoise_strength_index=0), x265=x265Settings(max_muxing_queue_size='1024', pix_fmt='yuv420p10le', extra='', extra_both_passes=False, name='HEVC (x265)', preset='medium', intra_encoding=False, profile='default', tune='default', hdr10=False, hdr10_opt=False, dhdr10_opt=False, repeat_headers=False, aq_mode=2, hdr10plus_metadata='', crf=22, bitrate=None, x265_params=[], bframes=4, lossless=False, b_adapt=2, intra_refresh=False, intra_smoothing=True, frame_threads=0, bitrate_passes=2), vvc=None, x264=None, rav1e=None, svt_av1=None, svt_av1_avif=None, vp9=None, aom_av1=None, gif=None, webp=None, copy_settings=None, ffmpeg_hevc_nvenc=None, qsvencc_hevc=None, qsvencc_av1=None, qsvencc_avc=None, nvencc_hevc=None, nvencc_avc=None, nvencc_av1=None, vceencc_hevc=None, vceencc_av1=None, vceencc_avc=None, hevc_videotoolbox=None, h264_videotoolbox=None, vaapi_h264=None, vaapi_hevc=None, vaapi_vp9=None, vaapi_mpeg2=None), 'UHD HDR10 Film': Profile(profile_version=1, auto_crop=True, fast_seek=True, rotate=0, vertical_flip=False, horizontal_flip=False, copy_chapters=True, remove_metadata=True, remove_hdr=False, encoder='HEVC (x265)', resolution_method='auto', resolution_custom=None, output_type='.mkv', audio_filters=None, audio_language=None, audio_select=None, audio_select_preferred_language=None, audio_select_first_matching=None, subtitle_language=None, subtitle_select=None, subtitle_select_preferred_language=None, subtitle_automatic_burn_in=None, subtitle_select_first_matching=None, advanced_options=AdvancedOptions(video_speed=1, deblock=None, deblock_size=16, tone_map='hable', vsync=None, brightness=None, saturation=None, contrast=None, maxrate=None, bufsize=None, source_fps=None, output_fps=None, color_space=None, color_transfer=None, color_primaries=None, denoise=None, denoise_type_index=0, denoise_strength_index=0), x265=x265Settings(max_muxing_queue_size='1024', pix_fmt='yuv420p10le', extra='', extra_both_passes=False, name='HEVC (x265)', preset='slow', intra_encoding=False, profile='default', tune='default', hdr10=True, hdr10_opt=True, dhdr10_opt=False, repeat_headers=True, aq_mode=2, hdr10plus_metadata='', crf=18, bitrate=None, x265_params=[], bframes=4, lossless=False, b_adapt=2, intra_refresh=False, intra_smoothing=True, frame_threads=0, bitrate_passes=2), vvc=None, x264=None, rav1e=None, svt_av1=None, svt_av1_avif=None, vp9=None, aom_av1=None, gif=None, webp=None, copy_settings=None, ffmpeg_hevc_nvenc=None, qsvencc_hevc=None, qsvencc_av1=None, qsvencc_avc=None, nvencc_hevc=None, nvencc_avc=None, nvencc_av1=None, vceencc_hevc=None, vceencc_av1=None, vceencc_avc=None, hevc_videotoolbox=None, h264_videotoolbox=None, vaapi_h264=None, vaapi_hevc=None, vaapi_vp9=None, vaapi_mpeg2=None), '1080p Film': Profile(profile_version=1, auto_crop=True, fast_seek=True, rotate=0, vertical_flip=False, horizontal_flip=False, copy_chapters=True, remove_metadata=True, remove_hdr=False, encoder='AVC (x264)', resolution_method='auto', resolution_custom=None, output_type='.mkv', audio_filters=None, audio_language=None, audio_select=None, audio_select_preferred_language=None, audio_select_first_matching=None, subtitle_language=None, subtitle_select=None, subtitle_select_preferred_language=None, subtitle_automatic_burn_in=None, subtitle_select_first_matching=None, advanced_options=AdvancedOptions(video_speed=1, deblock=None, deblock_size=16, tone_map='hable', vsync=None, brightness=None, saturation=None, contrast=None, maxrate=None, bufsize=None, source_fps=None, output_fps=None, color_space=None, color_transfer=None, color_primaries=None, denoise=None, denoise_type_index=0, denoise_strength_index=0), x265=None, vvc=None, x264=x264Settings(max_muxing_queue_size='1024', pix_fmt='yuv420p', extra='', extra_both_passes=False, name='AVC (x264)', preset='slow', profile='default', tune=None, crf=22, bitrate=None, bitrate_passes=2), rav1e=None, svt_av1=None, svt_av1_avif=None, vp9=None, aom_av1=None, gif=None, webp=None, copy_settings=None, ffmpeg_hevc_nvenc=None, qsvencc_hevc=None, qsvencc_av1=None, qsvencc_avc=None, nvencc_hevc=None, nvencc_avc=None, nvencc_av1=None, vceencc_hevc=None, vceencc_av1=None, vceencc_avc=None, hevc_videotoolbox=None, h264_videotoolbox=None, vaapi_h264=None, vaapi_hevc=None, vaapi_vp9=None, vaapi_mpeg2=None)} priority='Normal' stay_on_top=False portable_mode=False ui_scale='1' clean_old_logs=True sane_audio_selection=BoxList(['aac', 'ac3', 'alac', 'dca', 'dts', 'eac3', 'flac', 'libfdk_aac', 'libmp3lame', 'libopus', 'libvorbis', 'libwavpack', 'snoicls', 'sonic', 'truehd', 'tta']) vceencc_encoders=[] qsvencc_encoders=[] nvencc_encoders=[] vceencc_devices=Box({}) qsvencc_devices=Box({}) nvencc_devices=Box({}) sticky_tabs=False disable_complete_message=False disable_cover_extraction=False
Traceback (most recent call last):
  File "fastflix/widgets/progress_bar.py", line 96, in run
    task.command(config=self.app.fastflix.config, app=self.app, **task.kwargs)
  File "fastflix/flix.py", line 165, in ffmpeg_configuration
    raise FlixError(f'"{config.ffmpeg}" file not found or errored while executing. Return code {res.returncode}')
fastflix.exceptions.FlixError: "/usr/bin/ffmpeg" file not found or errored while executing. Return code 1
2024-09-14 19:59:25 nobara-pc fastflix[83861] ERROR Exception in 'run': "/usr/bin/ffmpeg" file not found or errored while executing. Return code 1 - args: (<fastflix.widgets.progress_bar.ProgressBar(0x10f94770, name="ProgressBar") at 0x7f194ea56780>,)
Traceback (most recent call last):
  File "reusables/wrappers.py", line 285, in wrapper
  File "fastflix/widgets/progress_bar.py", line 96, in run
    task.command(config=self.app.fastflix.config, app=self.app, **task.kwargs)
  File "fastflix/flix.py", line 165, in ffmpeg_configuration
    raise FlixError(f'"{config.ffmpeg}" file not found or errored while executing. Return code {res.returncode}')
fastflix.exceptions.FlixError: "/usr/bin/ffmpeg" file not found or errored while executing. Return code 1
2024-09-14 19:59:25 nobara-pc fastflix[83861] ERROR Could not start FastFlix!
Traceback (most recent call last):
  File "fastflix/application.py", line 228, in app_setup
    ProgressBar(app, startup_tasks)
  File "fastflix/widgets/progress_bar.py", line 64, in __init__
    self.run()
  File "reusables/wrappers.py", line 293, in wrapper
  File "reusables/wrappers.py", line 285, in wrapper
  File "fastflix/widgets/progress_bar.py", line 96, in run
    task.command(config=self.app.fastflix.config, app=self.app, **task.kwargs)
  File "fastflix/flix.py", line 165, in ffmpeg_configuration
    raise FlixError(f'"{config.ffmpeg}" file not found or errored while executing. Return code {res.returncode}')
fastflix.exceptions.FlixError: "/usr/bin/ffmpeg" file not found or errored while executing. Return code 1
2024-09-14 19:59:25 nobara-pc fastflix-core[83854] DEBUG Conversion worker shutting down
```

I'll go through and double check in a VM soon for weather its the same on a minimal install but I'm pretty sure it will be since this is only a day old install anyway lol

**Comment by BuyMyMojo** [comment]
Double checked, exact same error on a completely fresh VM

**Comment by cdgriffith** [comment]
Hi @BuyMyMojo  for distros other than Ubuntu you will probably need to run from source (see Run From Source section at bottom of release) 

https://github.com/cdgriffith/FastFlix/releases/tag/5.8.1

**Comment by Oroachi** [comment]
Hello,

I'm running into a very similar issue on Ubuntu 24.04.1 LTS and FastFlix 5.8.2:



tsunami@zima:~/Documents/FastFlix$ ./FastFlix 
2024-12-21 18:41:43 zima fastflix-core[484618] INFO Starting FastFlix 5.8.2
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_static_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
2024-12-21 18:41:43 zima fastflix[484624] DEBUG Using config file /home/tsunami/.local/share/FastFlix/fastflix.yaml
2024-12-21 18:41:43 zima fastflix[484624] INFO Checking for available NVEncC encoders
2024-12-21 18:41:43 zima fastflix[484624] INFO Running task Gather FFmpeg version
2024-12-21 18:41:43 zima fastflix[484624] INFO Running command: /usr/bin/ffmpeg -version
2024-12-21 18:41:43 zima fastflix[484624] ERROR /usr/bin/ffmpeg command stdout: 
2**024-12-21 18:41:43 zima fastflix[484624] ERROR /usr/bin/ffmpeg command stderr: /usr/bin/ffmpeg: /tmp/_MEIgBKig6/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /lib/x86_64-linux-gnu/libavfilter.so.9)
/usr/bin/ffmpeg: /tmp/_MEIgBKig6/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /lib/x86_64-linux-gnu/libjack.so.0)
/usr/bin/ffmpeg: /tmp/_MEIgBKig6/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /lib/x86_64-linux-gnu/librubberband.so.2)
/usr/bin/ffmpeg: /tmp/_MEIgBKig6/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /lib/x86_64-linux-gnu/libplacebo.so.338)
/usr/bin/ffmpeg: /tmp/_MEIgBKig6/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /lib/x86_64-linux-gnu/libopenmpt.so.0)
/usr/bin/ffmpeg: /tmp/_MEIgBKig6/libstdc++.so.6: version `GLIBCXX_3.4.31' not found (required by /lib/x86_64-linux-gnu/libopenmpt.so.0)
/usr/bin/ffmpeg: /tmp/_MEIgBKig6/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /lib/x86_64-linux-gnu/libchromaprint.so.1)
/usr/bin/ffmpeg: /tmp/_MEIgBKig6/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /lib/x86_64-linux-gnu/libsrt-gnutls.so.1.5)**

2024-12-21 18:41:43 zima fastflix[484624] ERROR Could not run task Gather FFmpeg version with config version='5.8.2' config_path=PosixPath('/home/tsunami/.local/share/FastFlix/fastflix.yaml') ffmpeg=PosixPath('/usr/bin/ffmpeg') ffprobe=PosixPath('/usr/bin/ffprobe') hdr10plus_parser=None nvencc=PosixPath('/usr/bin/nvencc') vceencc=None qsvencc=None output_directory=False source_directory=False output_name_format='{source}-fastflix-{rand_4}' flat_ui=True language='eng' logging_level=10 crop_detect_points=10 continue_on_failure=True work_path=PosixPath('/home/tsunami/.local/share/FastFlix') use_sane_audio=True selected_profile='UHD HDR10 Film' theme='onyx' disable_version_check=False disable_update_check=False disable_automatic_subtitle_burn_in=False custom_after_run_scripts=Box({}) profiles={'Standard Profile': Profile(profile_version=1, auto_crop=False, fast_seek=True, rotate=0, vertical_flip=False, horizontal_flip=False, copy_chapters=True, remove_metadata=True, remove_hdr=False, encoder='HEVC (x265)', resolution_method='auto', resolution_custom=None, output_type='.mkv', audio_filters=None, audio_language=None, audio_select=None, audio_select_preferred_language=None, audio_select_first_matching=None, subtitle_language=None, subtitle_select=None, subtitle_select_preferred_language=None, subtitle_automatic_burn_in=None, subtitle_select_first_matching=None, advanced_options=AdvancedOptions(video_speed=1, deblock=None, deblock_size=16, tone_map='hable', vsync=None, brightness=None, saturation=None, contrast=None, maxrate=None, bufsize=None, source_fps=None, output_fps=None, color_space=None, color_transfer=None, color_primaries=None, denoise=None, denoise_type_index=0, denoise_strength_index=0), x265=x265Settings(max_muxing_queue_size='1024', pix_fmt='yuv420p10le', extra='', extra_both_passes=False, name='HEVC (x265)', preset='medium', intra_encoding=False, profile='default', tune='default', hdr10=False, hdr10_opt=False, dhdr10_opt=False, repeat_headers=False, aq_mode=2, hdr10plus_metadata='', crf=22, bitrate=None, x265_params=[], bframes=4, lossless=False, b_adapt=2, intra_refresh=False, intra_smoothing=True, frame_threads=0, bitrate_passes=2), vvc=None, x264=None, rav1e=None, svt_av1=None, svt_av1_avif=None, vp9=None, aom_av1=None, gif=None, webp=None, copy_settings=None, ffmpeg_hevc_nvenc=None, qsvencc_hevc=None, qsvencc_av1=None, qsvencc_avc=None, nvencc_hevc=None, nvencc_avc=None, nvencc_av1=None, vceencc_hevc=None, vceencc_av1=None, vceencc_avc=None, hevc_videotoolbox=None, h264_videotoolbox=None, vaapi_h264=None, vaapi_hevc=None, vaapi_vp9=None, vaapi_mpeg2=None), 'UHD HDR10 Film': Profile(profile_version=1, auto_crop=True, fast_seek=True, rotate=0, vertical_flip=False, horizontal_flip=False, copy_chapters=True, remove_metadata=True, remove_hdr=False, encoder='HEVC (x265)', resolution_method='auto', resolution_custom=None, output_type='.mkv', audio_filters=None, audio_language=None, audio_select=None, audio_select_preferred_language=None, audio_select_first_matching=None, subtitle_language=None, subtitle_select=None, subtitle_select_preferred_language=None, subtitle_automatic_burn_in=None, subtitle_select_first_matching=None, advanced_options=AdvancedOptions(video_speed=1, deblock=None, deblock_size=16, tone_map='hable', vsync=None, brightness=None, saturation=None, contrast=None, maxrate=None, bufsize=None, source_fps=None, output_fps=None, color_space=None, color_transfer=None, color_primaries=None, denoise=None, denoise_type_index=0, denoise_strength_index=0), x265=x265Settings(max_muxing_queue_size='1024', pix_fmt='yuv420p10le', extra='', extra_both_passes=False, name='HEVC (x265)', preset='slow', intra_encoding=False, profile='default', tune='default', hdr10=True, hdr10_opt=True, dhdr10_opt=False, repeat_headers=True, aq_mode=2, hdr10plus_metadata='', crf=18, bitrate=None, x265_params=[], bframes=4, lossless=False, b_adapt=2, intra_refresh=False, intra_smoothing=True, frame_threads=0, bitrate_passes=2), vvc=None, x264=None, rav1e=None, svt_av1=None, svt_av1_avif=None, vp9=None, aom_av1=None, gif=None, webp=None, copy_settings=None, ffmpeg_hevc_nvenc=None, qsvencc_hevc=None, qsvencc_av1=None, qsvencc_avc=None, nvencc_hevc=None, nvencc_avc=None, nvencc_av1=None, vceencc_hevc=None, vceencc_av1=None, vceencc_avc=None, hevc_videotoolbox=None, h264_videotoolbox=None, vaapi_h264=None, vaapi_hevc=None, vaapi_vp9=None, vaapi_mpeg2=None), '1080p Film': Profile(profile_version=1, auto_crop=True, fast_seek=True, rotate=0, vertical_flip=False, horizontal_flip=False, copy_chapters=True, remove_metadata=True, remove_hdr=False, encoder='AVC (x264)', resolution_method='auto', resolution_custom=None, output_type='.mkv', audio_filters=None, audio_language=None, audio_select=None, audio_select_preferred_language=None, audio_select_first_matching=None, subtitle_language=None, subtitle_select=None, subtitle_select_preferred_language=None, subtitle_automatic_burn_in=None, subtitle_select_first_matching=None, advanced_options=AdvancedOptions(video_speed=1, deblock=None, deblock_size=16, tone_map='hable', vsync=None, brightness=None, saturation=None, contrast=None, maxrate=None, bufsize=None, source_fps=None, output_fps=None, color_space=None, color_transfer=None, color_primaries=None, denoise=None, denoise_type_index=0, denoise_strength_index=0), x265=None, vvc=None, x264=x264Settings(max_muxing_queue_size='1024', pix_fmt='yuv420p', extra='', extra_both_passes=False, name='AVC (x264)', preset='slow', profile='default', tune=None, crf=22, bitrate=None, bitrate_passes=2), rav1e=None, svt_av1=None, svt_av1_avif=None, vp9=None, aom_av1=None, gif=None, webp=None, copy_settings=None, ffmpeg_hevc_nvenc=None, qsvencc_hevc=None, qsvencc_av1=None, qsvencc_avc=None, nvencc_hevc=None, nvencc_avc=None, nvencc_av1=None, vceencc_hevc=None, vceencc_av1=None, vceencc_avc=None, hevc_videotoolbox=None, h264_videotoolbox=None, vaapi_h264=None, vaapi_hevc=None, vaapi_vp9=None, vaapi_mpeg2=None)} priority='Normal' stay_on_top=False portable_mode=False ui_scale='1' clean_old_logs=True sane_audio_selection=BoxList(['aac', 'ac3', 'alac', 'dca', 'dts', 'eac3', 'flac', 'libfdk_aac', 'libmp3lame', 'libopus', 'libvorbis', 'libwavpack', 'snoicls', 'sonic', 'truehd', 'tta']) vceencc_encoders=[] qsvencc_encoders=[] nvencc_encoders=[] vceencc_devices=Box({}) qsvencc_devices=Box({}) nvencc_devices={} sticky_tabs=False disable_complete_message=False disable_cover_extraction=False
Traceback (most recent call last):
  File "fastflix/widgets/progress_bar.py", line 96, in run
    task.command(config=self.app.fastflix.config, app=self.app, **task.kwargs)
  File "fastflix/flix.py", line 165, in ffmpeg_configuration
    raise FlixError(f'"{config.ffmpeg}" file not found or errored while executing. Return code {res.returncode}')
fastflix.exceptions.FlixError: "/usr/bin/ffmpeg" file not found or errored while executing. Return code 1
2024-12-21 18:41:43 zima fastflix[484624] ERROR Exception in 'run': "/usr/bin/ffmpeg" file not found or errored while executing. Return code 1 - args: (<fastflix.widgets.progress_bar.ProgressBar(0x25e20030, name="ProgressBar") at 0x72eb17648880>,)
Traceback (most recent call last):
  File "reusables/wrappers.py", line 285, in wrapper
  File "fastflix/widgets/progress_bar.py", line 96, in run
    task.command(config=self.app.fastflix.config, app=self.app, **task.kwargs)
  File "fastflix/flix.py", line 165, in ffmpeg_configuration
    raise FlixError(f'"{config.ffmpeg}" file not found or errored while executing. Return code {res.returncode}')
fastflix.exceptions.FlixError: "/usr/bin/ffmpeg" file not found or errored while executing. Return code 1
2024-12-21 18:41:43 zima fastflix[484624] ERROR Could not start FastFlix!
Traceback (most recent call last):
  File "fastflix/application.py", line 228, in app_setup
    ProgressBar(app, startup_tasks)
  File "fastflix/widgets/progress_bar.py", line 64, in __init__
    self.run()
  File "reusables/wrappers.py", line 293, in wrapper
  File "reusables/wrappers.py", line 285, in wrapper
  File "fastflix/widgets/progress_bar.py", line 96, in run
    task.command(config=self.app.fastflix.config, app=self.app, **task.kwargs)
  File "fastflix/flix.py", line 165, in ffmpeg_configuration
    raise FlixError(f'"{config.ffmpeg}" file not found or errored while executing. Return code {res.returncode}')
fastflix.exceptions.FlixError: "/usr/bin/ffmpeg" file not found or errored while executing. Return code 1
2024-12-21 18:41:43 zima fastflix-core[484618] DEBUG Conversion worker shutting down
tsunami@zima:~/Documents/FastFlix$ 


I have also verified that I have the requested GLIBCXX available as well:

tsunami@zima:~/Documents/FastFlix$ strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_3.4.26
GLIBCXX_3.4.27
GLIBCXX_3.4.28
GLIBCXX_3.4.29
GLIBCXX_3.4.30
**GLIBCXX_3.4.31
GLIBCXX_3.4.32**
GLIBCXX_3.4.33
GLIBCXX_TUNABLES
GLIBCXX_DEBUG_MESSAGE_LENGTH
tsunami@zima:~/Documents/FastFlix$

**Comment by Oroachi** [comment]
I forgot to include that im using the binary from FastFlix_5.8.2_ubuntu-22.04_x86_64.zip

**Comment by cdgriffith** [comment]
Will probably need to run from source for now (instructions on release page). Can start adding support for latest ubuntu with next release

**Comment by cdgriffith** [comment]
Hi @Oroachi the lastest release now has builds for Ubuntu 24.04! https://github.com/cdgriffith/FastFlix/releases/tag/5.9.0

**Comment by Oroachi** [comment]
It's looking great.

Thank you!
