### ISSUE TITLE
Bug: Crash when encoder switched to VP9 or GIF

### ISSUE THREAD

**Issue by L0Lock** [cdgriffith/FastFlix#62]
Using v2.6.0, FastFlix crashes when I set the encoder to GIF or VP9. Here are the console output:

GIF:
```python
Traceback (most recent call last):
  File "fastflix\widgets\video_options.py", line 46, in change_conversion
  File "fastflix\plugins\gif\settings_panel.py", line 89, in new_source
AttributeError: 'GIF' object has no attribute 'remove_hdr_label'
```

VP9:
```python
Traceback (most recent call last):
  File "fastflix\widgets\video_options.py", line 46, in change_conversion
  File "fastflix\plugins\vp9\settings_panel.py", line 251, in new_source
AttributeError: 'VP9' object has no attribute 'remove_hdr_label'
```

**Comment by cdgriffith** [comment]
Fixed in https://github.com/cdgriffith/FastFlix/releases/tag/2.6.1
