### ISSUE TITLE
Crash on startup when offline

### ISSUE THREAD

**Issue by L0Lock** [cdgriffith/FastFlix#79]
It seems that FastFlix crashes on startup whenever I'm offline. Tested on 3.0.0 and 3.0.2.

Command output:

```python
C:\AppInstl\FastFlix>fastflix
2020-10-11 10:44:04 DESKTOP-Chips fastflix-core[10980] INFO Starting FastFlix 3.0.2
2020-10-11 10:44:04 DESKTOP-Chips fastflix[3076] DEBUG Using qt engine pyqt5 version 5.15.1
2020-10-11 10:44:04 DESKTOP-Chips fastflix[3076] DEBUG Using config file "C:\Users\loicd\AppData\Roaming\FastFlix\fastflix.json"
2020-10-11 10:44:04 DESKTOP-Chips fastflix[3076] INFO Using FFmpeg C:\AppInstl\ffmpeg\bin\ffmpeg.exe
2020-10-11 10:44:04 DESKTOP-Chips fastflix[3076] INFO Using FFprobe C:\AppInstl\ffmpeg\bin\ffprobe.exe
2020-10-11 10:44:04 DESKTOP-Chips fastflix[3076] DEBUG running command: "C:\AppInstl\ffmpeg\bin\ffmpeg.exe" -version
2020-10-11 10:44:04 DESKTOP-Chips fastflix[3076] DEBUG running command: "C:\AppInstl\ffmpeg\bin\ffmpeg.exe" -hide_banner -filters
2020-10-11 10:44:04 DESKTOP-Chips fastflix[3076] DEBUG running command: "C:\AppInstl\ffmpeg\bin\ffprobe.exe" -version
2020-10-11 10:44:04 DESKTOP-Chips fastflix[3076] ERROR HARD FAIL: Unexpected error: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/cdgriffith/FastFlix/releases/latest (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A18C951D00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Traceback (most recent call last):
  File "urllib3\connection.py", line 159, in _new_conn
  File "urllib3\util\connection.py", line 61, in create_connection
  File "socket.py", line 918, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 670, in urlopen
  File "urllib3\connectionpool.py", line 381, in _make_request
  File "urllib3\connectionpool.py", line 978, in _validate_conn
  File "urllib3\connection.py", line 309, in connect
  File "urllib3\connection.py", line 171, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001A18C951D00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 726, in urlopen
  File "urllib3\util\retry.py", line 439, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/cdgriffith/FastFlix/releases/latest (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A18C951D00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fastflix\gui.py", line 263, in start_app
  File "fastflix\gui.py", line 243, in required_info
  File "fastflix\shared.py", line 88, in latest_fastflix
  File "requests\api.py", line 76, in get
  File "requests\api.py", line 61, in request
  File "requests\sessions.py", line 530, in request
  File "requests\sessions.py", line 643, in send
  File "requests\adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/cdgriffith/FastFlix/releases/latest (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A18C951D00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Unexpected error: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/cdgriffith/FastFlix/releases/latest (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A18C951D00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
```

**Comment by cdgriffith** [comment]
Well that's an issue. You can add `"disable_update_check": true` to the fastflix config file to disable update check until that's fixed.

**Comment by cdgriffith** [comment]
This should be fixed in https://github.com/cdgriffith/FastFlix/releases/tag/3.1.0
