### ISSUE TITLE
fastflix-3.2.0 - ModuleNotFoundError: No module named 'psutil'

### ISSUE THREAD

**Issue by I-Iawk** [cdgriffith/FastFlix#87]
```
Traceback (most recent call last):
  File "/home/********/.local/lib/python3.8/site-packages/fastflix/gui.py", line 40, in <module>
    from fastflix.widgets.command_runner import BackgroundRunner
  File "/home//********/./.local/lib/python3.8/site-packages/fastflix/widgets/command_runner.py", line 10, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
Could not load FastFlix properly!
```
Fresh install via **pip**, picked up this error.

**Comment by cdgriffith** [comment]
Thanks for the report, should be fixed now in 3.2.1  (pip only release)

**Comment by I-Iawk** [comment]
```
$ pip install --user fastflix==3.2.1
Collecting fastflix==3.2.1
  Using cached https://files.pythonhosted.org/packages/04/2f/2cef06ceaf0a7ce6b502e13d8318aa7b2db80ae8aade5fe79798e20ed7c1/fastflix-3.2.1-py3-none-any.whl
Requirement already satisfied: requests<3.0.0,>=2.24.0 in ./.local/lib/python3.8/site-packages (from fastflix==3.2.1) (2.24.0)
Requirement already satisfied: qtpy<2.0.0,>=1.9.0 in ./.local/lib/python3.8/site-packages (from fastflix==3.2.1) (1.9.0)
Requirement already satisfied: ruamel.yaml<0.17.0,>=0.16.10 in ./.local/lib/python3.8/site-packages (from fastflix==3.2.1) (0.16.12)
Requirement already satisfied: pyside2<6.0.0,>=5.15.0 in ./.local/lib/python3.8/site-packages (from fastflix==3.2.1) (5.15.1)
Requirement already satisfied: mistune<0.9.0,>=0.8.4 in ./.local/lib/python3.8/site-packages (from fastflix==3.2.1) (0.8.4)
Requirement already satisfied: coloredlogs<15.0,>=14.0 in ./.local/lib/python3.8/site-packages (from fastflix==3.2.1) (14.0)
Requirement already satisfied: appdirs<2.0.0,>=1.4.4 in ./.local/lib/python3.8/site-packages (from fastflix==3.2.1) (1.4.4)
Requirement already satisfied: reusables<0.10.0,>=0.9.5 in ./.local/lib/python3.8/site-packages (from fastflix==3.2.1) (0.9.6)
Requirement already satisfied: python-box[all]<6.0.0,>=5.1.1 in ./.local/lib/python3.8/site-packages (from fastflix==3.2.1) (5.1.1)
Collecting psutil<6.0.0,>=5.7.2
  Using cached https://files.pythonhosted.org/packages/aa/3e/d18f2c04cf2b528e18515999b0c8e698c136db78f62df34eee89cee205f1/psutil-5.7.2.tar.gz
Requirement already satisfied: certifi>=2017.4.17 in ./.local/lib/python3.8/site-packages (from requests<3.0.0,>=2.24.0->fastflix==3.2.1) (2020.6.20)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/lib/python3.8/site-packages (from requests<3.0.0,>=2.24.0->fastflix==3.2.1) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3.8/site-packages (from requests<3.0.0,>=2.24.0->fastflix==3.2.1) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3.8/site-packages (from requests<3.0.0,>=2.24.0->fastflix==3.2.1) (1.25.7)
Requirement already satisfied: ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.9" in ./.local/lib/python3.8/site-packages (from ruamel.yaml<0.17.0,>=0.16.10->fastflix==3.2.1) (0.2.2)
Requirement already satisfied: shiboken2==5.15.1 in ./.local/lib/python3.8/site-packages (from pyside2<6.0.0,>=5.15.0->fastflix==3.2.1) (5.15.1)
Requirement already satisfied: humanfriendly>=7.1 in ./.local/lib/python3.8/site-packages (from coloredlogs<15.0,>=14.0->fastflix==3.2.1) (8.2)
Requirement already satisfied: msgpack; extra == "all" in ./.local/lib/python3.8/site-packages (from python-box[all]<6.0.0,>=5.1.1->fastflix==3.2.1) (1.0.0)
Requirement already satisfied: toml; extra == "all" in ./.local/lib/python3.8/site-packages (from python-box[all]<6.0.0,>=5.1.1->fastflix==3.2.1) (0.10.1)
Installing collected packages: psutil, fastflix
    Running setup.py install for psutil ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w08lib91/psutil/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w08lib91/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-k0sffouf/install-record.txt --single-version-externally-managed --compile --user --prefix=
         cwd: /tmp/pip-install-w08lib91/psutil/
    Complete output (45 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/psutil
    copying psutil/_psosx.py -> build/lib.linux-x86_64-3.8/psutil
    copying psutil/_pssunos.py -> build/lib.linux-x86_64-3.8/psutil
    copying psutil/_pslinux.py -> build/lib.linux-x86_64-3.8/psutil
    copying psutil/_psaix.py -> build/lib.linux-x86_64-3.8/psutil
    copying psutil/__init__.py -> build/lib.linux-x86_64-3.8/psutil
    copying psutil/_psposix.py -> build/lib.linux-x86_64-3.8/psutil
    copying psutil/_common.py -> build/lib.linux-x86_64-3.8/psutil
    copying psutil/_compat.py -> build/lib.linux-x86_64-3.8/psutil
    copying psutil/_psbsd.py -> build/lib.linux-x86_64-3.8/psutil
    copying psutil/_pswindows.py -> build/lib.linux-x86_64-3.8/psutil
    creating build/lib.linux-x86_64-3.8/psutil/tests
    copying psutil/tests/runner.py -> build/lib.linux-x86_64-3.8/psutil/tests
    copying psutil/tests/test_contracts.py -> build/lib.linux-x86_64-3.8/psutil/tests
    copying psutil/tests/__main__.py -> build/lib.linux-x86_64-3.8/psutil/tests
    copying psutil/tests/test_linux.py -> build/lib.linux-x86_64-3.8/psutil/tests
    copying psutil/tests/test_process.py -> build/lib.linux-x86_64-3.8/psutil/tests
    copying psutil/tests/test_osx.py -> build/lib.linux-x86_64-3.8/psutil/tests
    copying psutil/tests/__init__.py -> build/lib.linux-x86_64-3.8/psutil/tests
    copying psutil/tests/test_sunos.py -> build/lib.linux-x86_64-3.8/psutil/tests
    copying psutil/tests/test_misc.py -> build/lib.linux-x86_64-3.8/psutil/tests
    copying psutil/tests/test_windows.py -> build/lib.linux-x86_64-3.8/psutil/tests
    copying psutil/tests/test_posix.py -> build/lib.linux-x86_64-3.8/psutil/tests
    copying psutil/tests/test_unicode.py -> build/lib.linux-x86_64-3.8/psutil/tests
    copying psutil/tests/test_memleaks.py -> build/lib.linux-x86_64-3.8/psutil/tests
    copying psutil/tests/test_connections.py -> build/lib.linux-x86_64-3.8/psutil/tests
    copying psutil/tests/test_bsd.py -> build/lib.linux-x86_64-3.8/psutil/tests
    copying psutil/tests/test_testutils.py -> build/lib.linux-x86_64-3.8/psutil/tests
    copying psutil/tests/test_system.py -> build/lib.linux-x86_64-3.8/psutil/tests
    copying psutil/tests/test_aix.py -> build/lib.linux-x86_64-3.8/psutil/tests
    running build_ext
    building 'psutil._psutil_linux' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/psutil
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=572 -DPSUTIL_LINUX=1 -I/usr/include/python3.8 -c psutil/_psutil_common.c -o build/temp.linux-x86_64-3.8/psutil/_psutil_common.o
    psutil/_psutil_common.c:9:10: fatal error: Python.h: No such file or directory
        9 | #include <Python.h>
          |          ^~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w08lib91/psutil/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w08lib91/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-k0sffouf/install-record.txt --single-version-externally-managed --compile --user --prefix= Check the logs for full command output.
```

Testing out 3.2.1 build and got the following error now.

Let me know if you need more logs in order to help troubleshoot this for you if any.

**Comment by cdgriffith** [comment]
Oh bummer, didn't realize `psutil` required dev files to build on linux :( 

Ubuntu
```
sudo apt install gcc python3-dev
```

Red Hat
```
sudo yum install gcc python3-devel
```

And apparently requires Xcode on Mac, blea. Will work on trying to find better solutions for those platforms

**Comment by cdgriffith** [comment]
The [readme](https://github.com/cdgriffith/FastFlix#macos-and-linux) has been updated to contain that information now. I hope that I will be able to figure out a way to use FFmpeg's built in pause capabilities instead of needing `psutil` in the future, but I have already spent a few days looking before going to `psutil` so may take a while.
